name: Trahl tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Cache test environment
      - name: Cache test environment
        uses: actions/cache@v4
        with:
          path: test-resources
          key: test-resources-${{ hashFiles('prepare-test-env.sh') }}
          restore-keys: |
            test-resources-

      - name: Prepare test environment
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          tar -xf ffmpeg-release-amd64-static.tar.xz
          sudo cp ffmpeg-*/ffmpeg /usr/local/bin/
          sudo cp ffmpeg-*/ffprobe /usr/local/bin/
          chmod +x prepare-test-env.sh
          ./prepare-test-env.sh

      # Cache cargo registry
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # Cache cargo build
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install cargo-nextest
        run: cargo install cargo-nextest

      - name: Run tests with nextest
        run: |
          cargo nextest run --all --reporter json > nextest-report.json || true

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: nextest-report
          path: nextest-report.json

