name: Trahl tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      # Cache test environment
      - name: Cache test environment
        id: test-env-cache
        uses: actions/cache@v4
        with:
          path: test-resources
          key: test-resources-${{ hashFiles('prepare-test-env.sh') }}
          restore-keys: |
            test-resources-
 
      - name: Prepare test environment
        if: steps.test-env-cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -f test-resources/ffmpeg/ffmpeg ]; then
            wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            tar -xf ffmpeg-release-amd64-static.tar.xz
            mkdir -p test-resources/ffmpeg
            cp ffmpeg-*/ffmpeg ffmpeg-*/ffprobe test-resources/ffmpeg/
          fi
          cp test-resources/ffmpeg/ffmpeg /usr/local/bin/
          cp test-resources/ffmpeg/ffprobe /usr/local/bin/
          chmod +x prepare-test-env.sh
          ./prepare-test-env.sh

      # Cache cargo registry
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      # Cache cargo build
      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Cache cargo bin
        id: cargo-bin-cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}-v0
          restore-keys: |
            cargo-bin-${{ runner.os }}-

      - name: Install cargo-nextest
        if: steps.cargo-bin-cache.outputs.cache-hit != 'true'
        run: cargo install cargo-nextest

      - name: Run tests with nextest
        run: |
          cargo nextest run --no-fail-fast
